# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0767d982a1bc98ff4f6edf281a0e33c"
name = "ccp"
handle = "ccp-6"
application_url = "https://alfred-investigations-worst-letters.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://alfred-investigations-worst-letters.trycloudflare.com/auth/callback", "https://alfred-investigations-worst-letters.trycloudflare.com/auth/shopify/callback", "https://alfred-investigations-worst-letters.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
